// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6nDq6T1QS8otat18zQNoeWtevAULcL4',
    appId: '1:95930596648:web:2ddf90bd821b3f4674641d',
    messagingSenderId: '95930596648',
    projectId: 'venue-book-6548b',
    authDomain: 'venue-book-6548b.firebaseapp.com',
    storageBucket: 'venue-book-6548b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaAXCMWOJPF6OcKLVLG3Vxl7Z8wfUwAyw',
    appId: '1:95930596648:android:0bc17f3d7a01689274641d',
    messagingSenderId: '95930596648',
    projectId: 'venue-book-6548b',
    storageBucket: 'venue-book-6548b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIJFBp4Hup3WH0qKF2hSQYGDsdF39QA3I',
    appId: '1:95930596648:ios:78e77d389a8b943774641d',
    messagingSenderId: '95930596648',
    projectId: 'venue-book-6548b',
    storageBucket: 'venue-book-6548b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIJFBp4Hup3WH0qKF2hSQYGDsdF39QA3I',
    appId: '1:95930596648:ios:78e77d389a8b943774641d',
    messagingSenderId: '95930596648',
    projectId: 'venue-book-6548b',
    storageBucket: 'venue-book-6548b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd6nDq6T1QS8otat18zQNoeWtevAULcL4',
    appId: '1:95930596648:web:6ab80b3698cc8c6e74641d',
    messagingSenderId: '95930596648',
    projectId: 'venue-book-6548b',
    authDomain: 'venue-book-6548b.firebaseapp.com',
    storageBucket: 'venue-book-6548b.firebasestorage.app',
  );
}
